ansible: upgrade to 8.7.0

diff --git a/install b/install
--- a/install
+++ b/install
@@ -14,7 +14,7 @@ symlinked_commands=(
 )
 readonly symlinked_commands
 
-# equivalent to readlink -f
+# cross-platform equivalent to GNU readlink -f.
 canonicalize() {
   local t
   t="$1"
@@ -50,14 +50,6 @@ Ansible commands:
 Symlink installation will be skipped if the file already exists and is not
 already a symlink to TARGET/${script} and --force is not supplied.
 USAGE
-}
-
-maybe-verbose() {
-  if "${verbose}"; then
-    set -x && "${@}" && set +x
-  else
-    "${@}"
-  fi
 }
 
 declare force install_symlinks no_download target target_script verbose
@@ -104,25 +96,35 @@ fi
 target_script="${target}/${script}"
 
 download-script() {
-  if ! curl -sSL --fail "${url}" -o "${target_script}"; then
+  local -a cmd
+  cmd=(curl -sSL --fail "${url}" -o "${target_script}")
+
+  [[ "${verbose}" ]] && echo "${cmd[*]}"
+
+  if ! "${cmd[@]}"; then
     echo >&2 "error: could not download ${url} into ${target_script}."
     exit 1
   fi
 }
 
-if "${no_download}"; then
+if "${no_download}" && ! [[ -x "${target_script}" ]]; then
+  echo >&2 "error: ${target_script} does not exist and no download is set."
+  exit 1
+elif [[ -x "${target_script}" ]] && ! "${force}"; then
+  echo >&2 "error: ${target_script} already exists."
+  exit 1
+fi
+
+if ! [[ -x "${target_script}" ]] && ! "${no_download}"; then
+  download-script
+
   if ! [[ -x "${target_script}" ]]; then
-    echo >&2 "error: ${target_script} does not exist and no download is set."
+    if "${verbose}"; then
+      chmod -v +x "${target_script}"
+    else
+      chmod +x "${target_script}"
+    fi
   fi
-elif [[ -x "${target_script}" ]]; then
-  if ! "${force}"; then
-    echo >&2 "error: ${target_script} already exists."
-    exit 1
-  fi
-
-  maybe-verbose download-script
-
-  [[ -x "${target_script}" ]] || maybe-verbose chmod +x "${target_script}"
 fi
 
 "${install_symlinks}" || exit 0
@@ -140,5 +142,9 @@ for symlinked_command in "${symlinked_commands[@]}"; do
     fi
   fi
 
-  maybe-verbose ln -sf "${target_script}" "${target_command}"
+  if "${verbose}"; then
+    ln -sfv "${target_script}" "${target_command}"
+  else
+    ln -sf "${target_script}" "${target_command}"
+  fi
 done
